import Head from "next/head";
import React from 'react';
import NavBar from '@/components/nav/header';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import Login from '@/components/users/login';
import SignUp from '@/components/users/signup';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

export default function Home() {
    const { t } = useTranslation();

    return (
        <>
            <Head>
                <title>Account</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <NavBar />
                <div className="flex justify-center">
                    <Tabs defaultValue="create" className="w-[350px]">
                        <TabsList className="grid w-full grid-cols-2">
                            <TabsTrigger value="login">{
                                // @ts-ignore
                                t("account.login")
                            }</TabsTrigger>
                            <TabsTrigger value="create">{
                                // @ts-ignore
                                t("account.sign_up")
                            }</TabsTrigger>
                        </TabsList>
                        <TabsContent value="login">
                            <Login />
                        </TabsContent>
                        <TabsContent value="create">
                            <SignUp />
                        </TabsContent>
                    </Tabs>
                </div>
            </main>
        </>
    );
}

// @ts-ignore
export const getServerSideProps = async (context) => {
    const { locale } = context;

    return {
        props: {
            ...(await serverSideTranslations(locale ?? "en", ["common"])),
        },
    };
}