import Head from "next/head";
import Header from '@/components/nav/header';
import React from 'react';
import { Theme } from '@radix-ui/themes';
import NavBar from '@/components/nav/header';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import Login from '@/components/users/login';
import SignUp from '@/components/users/signup';

export default function Home() {
        return (
            <>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main>
                    <NavBar />
                    <div className="flex justify-center">
                        <Tabs defaultValue="create" className="w-[350px]">
                            <TabsList className="grid w-full grid-cols-2">
                                <TabsTrigger value="login">Login</TabsTrigger>
                                <TabsTrigger value="create">Sign up</TabsTrigger>
                            </TabsList>
                            <TabsContent value="login">
                                <Login />
                            </TabsContent>
                            <TabsContent value="create">
                                <SignUp />
                            </TabsContent>
                        </Tabs>
                    </div>
                </main>
            </>
        );
}
