import Head from "next/head";
import Header from '@/components/nav/header';
import React from 'react';
import { Theme } from '@radix-ui/themes';
import NavBar from '@/components/nav/header';

export default function Home() {
        return (
            <>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main>
                    <NavBar></NavBar>
                </main>
            </>
        );
}
